# Generated by Django 5.1.7 on 2025-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], default='MALE', max_length=10)),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('USER', 'user')], default='USER', max_length=10)),
            ],
        ),
    ]
